export enum ActionTypes {
  CHANGE_NEW_BOOK = 'NEW_BOOK/CHANGE_NEW_BOOK',
  FETCH_STARTED = 'NEW_BOOK/FETCH_STARTE',
  FETCH_SUCCESS='NEW_BOOK/FETCH_SUCCESS',
  FETCH_FAILURE = 'NEW_BOOK/FETCH_FAILURE'
}