enum ActionTypes {
  CHANGE_VALUE = 'SEARCH/CHANGE_VALUE',
  CHANGE_HISTORY_SEARCH = 'SEARCH/CHANGE_HISTORY_SEARCH',
  CHANGE_NOW_SEARCH = 'SEARCH/CHANGE_NOW_SEARCH',
  FETCH_STARTED = 'SEARCH/FETCH_STARTE',
  FETCH_SUCCESS='SEARCH/FETCH_SUCCESS',
  FETCH_FAILURE = 'SEARCH/FETCH_FAILURE'
}
export default ActionTypes
